# .github/workflows/backend-deploy.yml
name: Deploy Backend to Render

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'  # Only trigger on changes to server directory

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}